/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entity.PedidoBean;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import main.Utils;

/**
 *
 * @author eduar
 */
public class Form extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupDistribuidor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombreMedicamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbBoxTipoMedicamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        radioBtnCofarma = new javax.swing.JRadioButton();
        radioBtnEmpsephar = new javax.swing.JRadioButton();
        radioBtnCemefar = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chckPrincipal = new javax.swing.JCheckBox();
        chckSecundaria = new javax.swing.JCheckBox();
        btnBorrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(340, 460));
        setRequestFocusEnabled(false);

        jLabel1.setText("Nombre del medicamento:");

        jLabel2.setText("Tipo de medicamento:");

        cmbBoxTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));

        jLabel3.setText("Cantidad de producto:");

        groupDistribuidor.add(radioBtnCofarma);
        radioBtnCofarma.setText("Cofarma");

        groupDistribuidor.add(radioBtnEmpsephar);
        radioBtnEmpsephar.setText("Empsephar");

        groupDistribuidor.add(radioBtnCemefar);
        radioBtnCemefar.setText("Cemefar");

        jLabel4.setText("Distribuidor a pedir:");

        jLabel5.setText("Sucursal que requiere el medicamento:");

        chckPrincipal.setText("Principal");

        chckSecundaria.setText("Secundaria");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Confirmar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckSecundaria)
                    .addComponent(chckPrincipal)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioBtnCemefar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioBtnEmpsephar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioBtnCofarma, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombreMedicamento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbBoxTipoMedicamento, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                        .addComponent(txtCantidadProducto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBoxTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnCofarma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnEmpsephar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnCemefar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnAceptar))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        List<String> errores = validarInput();
        
        if (errores.isEmpty()) {
            JDialog modal = new ModalPedido(parentFrame, true, getPedido());
            modal.setVisible(true);
        } else {
            JDialog modalError = new ModalError(parentFrame, true, errores);
            modalError.setVisible(true);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtNombreMedicamento.setText("");
        cmbBoxTipoMedicamento.setSelectedIndex(0);
        groupDistribuidor.clearSelection();
        txtCantidadProducto.setText("");
        chckPrincipal.setSelected(false);
        chckSecundaria.setSelected(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private List<String> validarInput() {
        List<String> mensajesError = new ArrayList<>();
        
        if (txtNombreMedicamento.getText().equals("")) {
            mensajesError.add("El nombre del medicamento esta vacio");
        }
        
        Pattern patron = Pattern.compile("^[a-zA-Z0-9 ]*$");
        Matcher verificar = patron.matcher(txtNombreMedicamento.getText());
        
        if (!verificar.matches()) {
            mensajesError.add("El nombre del medicamento solo debe contener caracteres alfanumericos");
        }
        
        if (cmbBoxTipoMedicamento.getSelectedIndex() == 0) {
            mensajesError.add("El tipo de medicamento no ha sido selecionado");
        }
        
        int cantidadPedido = Utils.tryParseInt(txtCantidadProducto.getText());
        if (cantidadPedido == -1) {
            mensajesError.add("La cantidad de medicamento no es un numero valido");
        }
        
        boolean noProveedorSeleccionado = true;
        for (Enumeration<AbstractButton> buttons = groupDistribuidor.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            
            if (button.isSelected()) {
                noProveedorSeleccionado = false;
            }
        }
        
        if (noProveedorSeleccionado) {
            mensajesError.add("No se ha seleccionado un proveedor");
        }
        
        if (!chckPrincipal.isSelected() && !chckSecundaria.isSelected()) {
            mensajesError.add("No se ha seleccionado una succursal");
        }
        
        return mensajesError;
    }
    
    private PedidoBean getPedido() {
        
        PedidoBean pedido = new PedidoBean();
        pedido.setNombreMedicamento(txtNombreMedicamento.getText());
        pedido.setTipoMedicamento(cmbBoxTipoMedicamento.getSelectedItem().toString());
        
        int cantidadMedNum = Integer.parseInt(txtCantidadProducto.getText());
        pedido.setCantidadMedicamento(cantidadMedNum);
        
        for (Enumeration<AbstractButton> buttons = groupDistribuidor.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            
            if (button.isSelected()) {
                pedido.setDistribuidor(button.getText());
            }
        }
        
        List<String> sucursalesSelecionadas = new ArrayList<>();
        if (chckPrincipal.isSelected())
            sucursalesSelecionadas.add("Calle de la Rosa n. 28");
        
        if (chckSecundaria.isSelected())
            sucursalesSelecionadas.add("Calle Alcazabilla n. 3");
        
        pedido.setSucursalesADistribuir(sucursalesSelecionadas);
        return pedido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JCheckBox chckPrincipal;
    private javax.swing.JCheckBox chckSecundaria;
    private javax.swing.JComboBox<String> cmbBoxTipoMedicamento;
    private javax.swing.ButtonGroup groupDistribuidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioBtnCemefar;
    private javax.swing.JRadioButton radioBtnCofarma;
    private javax.swing.JRadioButton radioBtnEmpsephar;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtNombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
